"""
Shared texture props for every room.

The generated materials live in roomsrc/tex/ and are content-addressed into
the world asset store, then handed to each app as props so a script can do
`props.plaster.url` without knowing any hashes.
"""
import hashlib
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
HQ = os.path.dirname(ROOT)
ASSETS = os.path.join(HQ, 'world', 'assets')

# prop name -> (file, type)
TEXTURES = {
    'paving':      ('t_paving.jpg',       'image'),
    'pavingRoom':  ('t_paving_room.jpg',  'image'),
    'plaster':     ('t_plaster.jpg',      'image'),
    'wainscot':    ('t_wainscot.jpg',     'image'),
    'marbleFloor': ('t_marble_floor.jpg', 'image'),
    'marbleWall':  ('t_marble_wall.jpg',  'image'),
    'wood':        ('t_wood.jpg',         'image'),
    'soil':        ('t_soil.jpg',         'image'),
    'skyBg':       ('sky_bg.jpg',         'image'),
    'skyHdr':      ('sky_env.hdr',        'hdr'),
}

# The playable cast. Cash Cat is the real brand image; the rest are generated
# to match it (prompts in cast/prompts).
CAST = {
    'catLong':    'cast/cat_long.png',
    'catSerious': 'cast/cat_serious.png',
    'catApple':   'cast/cat_apple.png',
    'catPop':     'cast/cat_pop.png',
}


def put(path, ext):
    d = open(path, 'rb').read()
    h = hashlib.sha256(d).hexdigest()
    dst = os.path.join(ASSETS, '%s.%s' % (h, ext))
    if not os.path.exists(dst):
        open(dst, 'wb').write(d)
    return 'asset://%s.%s' % (h, ext)


def props(names=None):
    out = {}
    for key, (fname, kind) in TEXTURES.items():
        if names and key not in names:
            continue
        ext = fname.rsplit('.', 1)[1]
        url = put(os.path.join(ROOT, 'tex', fname), ext)
        out[key] = {'type': kind, 'name': fname, 'url': url}
    return out


def cast():
    """Portraits of the playable cats, plus Cash Cat from the brand assets."""
    out = {}
    for key, rel in CAST.items():
        url = put(os.path.join(ROOT, rel), 'png')
        out[key] = {'type': 'image', 'name': os.path.basename(rel), 'url': url}
    url = put(os.path.join(HQ, '..', 'assets', 'cashcat.png'), 'png')
    out['catCash'] = {'type': 'image', 'name': 'cashcat.png', 'url': url}
    return out


# The same five cats as wearable avatars. Generated by tripo_cats.py and
# converted by glb2vrm.py, which is where all the rig correction lives.
AVATARS = {
    'avCash':    'cat_cash.vrm',
    'avLong':    'cat_long.vrm',
    'avSerious': 'cat_serious.vrm',
    'avApple':   'cat_apple.vrm',
    'avPop':     'cat_pop.vrm',
}


def avatars():
    """
    Wearable versions of the cast, keyed the same way as the portraits.

    Missing files are skipped rather than fatal: the .vrm files are generated
    and gitignored, so a fresh clone has the scripts but not the models, and
    a room that quietly offers four cats instead of five is better than an
    install that refuses to run at all.
    """
    out = {}
    for key, fname in AVATARS.items():
        path = os.path.join(ROOT, 'cast_vrm', fname)
        if not os.path.exists(path):
            continue
        out[key] = {'type': 'avatar', 'name': fname, 'url': put(path, 'vrm')}
    return out


# Models from the fetched CC0 packs (roomsrc/packs, see fetch_packs.py).
# Keyed m_<name> so a script can say props.m_towerA.url without knowing which
# pack it came from or what the file is called.
MODELS = {
    # the city that surrounds the campus
    'm_bldA':   'city-kit-commercial/building-a.glb',
    'm_bldB':   'city-kit-commercial/building-c.glb',
    'm_bldC':   'city-kit-commercial/building-f.glb',
    'm_bldD':   'city-kit-commercial/building-j.glb',
    'm_bldE':   'city-kit-commercial/building-n.glb',
    'm_towerA': 'city-kit-commercial/building-skyscraper-a.glb',
    'm_towerB': 'city-kit-commercial/building-skyscraper-c.glb',
    'm_towerC': 'city-kit-commercial/building-skyscraper-e.glb',
    'm_lamp':   'city-kit-roads/light-square-double.glb',
    'm_bin':    'city-kit-roads/dumpster.glb',
    # planting
    'm_tree':   'nature-kit/tree_default.glb',
    'm_treeB':  'nature-kit/tree_detailed.glb',
    'm_pine':   'nature-kit/tree_cone.glb',
    'm_bush':   'nature-kit/plant_bushLarge.glb',
    'm_rock':   'nature-kit/rock_largeA.glb',
    'm_grass':  'nature-kit/grass_large.glb',
    # the fishing spot
    'm_dock':   'pirate-kit/tower-base.glb',
    'm_boat':   'pirate-kit/boat-row-small.glb',
    'm_palm':   'pirate-kit/palm-detailed-straight.glb',
    'm_barrel': 'pirate-kit/barrel.glb',
}


def models(names=None):
    """
    Pack models as props. Missing files are skipped rather than fatal — the
    packs are fetched, not committed, so a fresh clone has the script and not
    yet the assets, and a plaza with no trees beats an install that refuses
    to run. Run fetch_packs.py to fill them in.
    """
    out = {}
    for key, rel in MODELS.items():
        if names and key not in names:
            continue
        path = os.path.join(ROOT, 'packs', rel)
        if not os.path.exists(path):
            continue
        out[key] = {'type': 'model', 'name': os.path.basename(rel),
                    'url': put(path, 'glb')}
    return out
